### PR TITLE
Mutual Information estimates tutorial and benchmarks (Fig. 3 in Uncertainty Forest)

### PR DESCRIPTION
**Pull request by EYezerets**
#### Reference issue
Closes "re-write all the UF notebooks called ProgL repo functions [#62](https://github.com/neurodata/ProgLearn/issues/62)"
Closes "make 3 tutorials to run the experiments from uncertainty-forests [#37](https://github.com/neurodata/ProgLearn/issues/37)"

#### Type of change

Documentation

#### What does this implement/fix?
I added a tutorial and a benchmarks notebook to present the mutual information estimates from Fig. 3 in the [uncertainty forest paper](https://arxiv.org/abs/1907.00325). This should be the last set of notebooks documenting the figures in that paper.

### CODE REVIEW

**Comment by EYezerets** [comment]
One question: is the tutorial figure OK as-is? I used the same plotting functions for the benchmarks and tutorials, and obviously they were designed to look good for the full data rather than the test data, so the figure produced by the tutorial notebook doesn't look as good in terms of axis scaling.

**Review by PSSF23 — COMMENTED** [review]
@EYezerets Looks good to me except the warnings in `conditionalentropyestimates` tutorial and especially benchmark. Could you try to remove them? Or I can hackingly delete them from the notebooks...

Also does this PR close #37 as well?

**Comment by EYezerets** [comment]
@PSSF23 I'm afraid it would have to be a hacky way I think, I'm not sure how to suppress those warnings unless you have a suggestion? I also wouldn't want to rerun them if I don't have to - they take hours/overnight on AWS. I just updated the PR description as you suggested, thanks for the reminder about issue 37.

**Comment by PSSF23** [comment]
@EYezerets The hacking removal is done. I have not done hiding warnings before but [this post](https://stackoverflow.com/questions/9031783/hide-all-warnings-in-ipython) seems helpful.

**Comment by EYezerets** [comment]
@PSSF23 thank you so much! May I ask what you did to remove the warnings post-factum? Did you just go into the raw file for the notebooks? Or we can chat offline if that's more convenient so as not to clutter this PR

**Comment by levinwil** [comment]
@EYezerets I have no idea what "real" parameters and "test" parameters are. What does that mean? If you are using some parameters to reproduce paper results, call those parameters "paper reproduction" parameters and parameters for faster experimentation something that indicates what it's doing. Or, in the notebook, just have the parameters for faster experimentation, and just have the paper reproduction parameters in benchmarks.

**Comment by EYezerets** [comment]
Oh OK thanks, I will fix that in all the tutorials @levinwil

**Comment by levinwil** [comment]
@PSSF23 Does this look good to you? It looks good to me

**Review by PSSF23 — APPROVED** [review]
@levinwil Looks good to me, too.

**Pull request merged**
