### PR TITLE
Simplify rotation_cifar tutorial and move functions to a separate file

### PR DESCRIPTION
**Pull request by srahul1222**
#### Reference issue
Closes Issue #305 

#### Type of change
Feature Request

#### What does this implement/fix?
Most functions were moved to a separate file in the tutorials/functions folder. The notebook now only contains the code needed to actually run the experiment and visualize the results.

### CODE REVIEW

**Review by levinwil — CHANGES_REQUESTED** [review]
Also, please get rid of the unnecessary code in the rotation_cifar_functions.py file

There are a bunch of unnecessary imports, and a specification of tf GPU on line 78 - both are unnecessary.

**Comment by levinwil** [comment]
@srahul1222 why did you close this?

**Comment by srahul1222** [comment]
@levinwil oh my bad, I thought I was supposed to PR into the docs branch instead but I just saw your slack message about PR'ing into staging

**Comment by levinwil** [comment]
@srahul1222 Ah I see. Feel free to resubmit the PR however you'd like. Please make sure it's a PR into staging with the tutorial under 'docs/tutorials'

**Pull request closed without merging**
