### PR TITLE
Add Streaming Function

### PR DESCRIPTION
**Pull request by KevinWang905**
Reference issue
Add streaming from sklearn-stream to Proglearn

Type of change
Feature Request

What does this implement/fix?
Changes to progressive_learner.py, voters.py, forest.py, and transformers.py. Implements function update_task() that allows for data streaming using the partial_fit function from scikit-learn.

Additional information

### CODE REVIEW

**Review by PSSF23 — CHANGES_REQUESTED** [review]
First thing. `black` format your file. Then look over @nhahn7's code experiment notebook here: https://github.com/neurodata/SDTF/blob/main/docs/xor_experiments.ipynb

Run the notebook & make another PR to https://github.com/neurodata/SDTF

**Comment by nhahn7** [comment]
> First thing. `black` format your file. Then look over @nhahn7's code experiment notebook here: https://github.com/neurodata/SDTF/blob/main/docs/xor_experiments.ipynb
> 
> Run the notebook & make another PR to https://github.com/neurodata/SDTF

@KevinWang905  One quick note before running the experiments. You'll need to make an empty folder in SDTF called `benchmarks/results/synf` or else you'll get errors when writing the results for synergistic forest since that folder currently doesn't exist. The results for all other classifiers are already stored in results and do not need to be ran again.

**Comment by nhahn7** [comment]
@KevinWang905 @PSSF23 After looking at synf results I realized I needed to make some changes to the experiment code. I updated the experiment code [here](https://github.com/nhahn7/SDTF/tree/ODIF)

Should I make a PR with the changes? and if so, should I run the experiments? or just update the code if Kevin you want to run them? Let me know what you guys think

**Comment by PSSF23** [comment]
@nhahn7 Totally good for you to make another PR! I don't mind either of you runs the experiments as long as you two talk it through before hand.

**Pull request closed without merging**
