### PR TITLE
Scene segmentation tutorial

### PR DESCRIPTION
**Pull request by amyvanee**
#### Reference issue
Issue #39 

#### Type of change
Added a Python notebook.

#### What does this implement/fix?
Added a tutorial on scene segmentation.

#### Additional information
Contributors: Narayani Wagle (@nhwagle) and Amy van Ee (@amyvanee)

### CODE REVIEW

**Review by PSSF23 — CHANGES_REQUESTED** [review]
`black` format needed for both files.

**Review by PSSF23 — CHANGES_REQUESTED** [review]
The image directories are not necessary outputs, so they should be removed.

**Review by PSSF23 — CHANGES_REQUESTED** [review]
@amyvanee @nhwagle 

- Remove unnecessary outputs (like your file directories)
- Add tutorial name to **the list mentioned in guidelines**

**Comment by jdey4** [comment]
@amyvanee please take out the mention of proglearn at the end.

**Comment by amyvanee** [comment]
@jdey4  Thank you! Do you want me to remove the last sentence as well, "This thus presents an opportunity for Proglearn to allow for improved and more generalizable scene segmentation."?

**Review by jdey4 — APPROVED** [review]

**Comment by jdey4** [comment]
@PSSF23 are your requested changes done?

**Review by PSSF23 — APPROVED** [review]

**Pull request merged**
