### PR TITLE
Make the array-ness of self.classes explicit

### PR DESCRIPTION
**Pull request by levinwil**
Indexing into a list using an array of integers does not work and for some reason in my use case that's what self.classes is. This simply makes the array-ness of self.classes explicit.

#### Type of change

Bug 

#### What does this implement/fix?

Ensures that voter output can be indexed, even if the `classes` provided in the class are not numpy arrays

### CODE REVIEW

**Review by PSSF23 — APPROVED** [review]
@levinwil I noticed that this syntax: `np.asarray(self.classes)` is used in the `fit` [function](https://github.com/neurodata/ProgLearn/blob/staging/proglearn/voters.py#L67) as well. So would it be simpler to initialize `classes` as `np.asarray`? Something like such:

```python
  def __init__(self, kappa=np.inf, classes=[]):
      self.kappa = kappa
      self.classes = np.asarray(classes)
```

**Comment by levinwil** [comment]
@PSSF23 yup! That makes sense as well!

**Comment by levinwil** [comment]
@PSSF23 Just made the simplification changes. Should take a few mins to run checks.

**Comment by PSSF23** [comment]
@levinwil I updated the `KNNClassificationVoter` initialization to resolve the error~

**Pull request merged**
