### PR TITLE
Add max_depth as a parameter to LifelongClassificationForest and UncertaintyForest

### PR DESCRIPTION
**Pull request by srahul1222**
#### Reference issue
Closes Issue #247 

#### Type of change
Feature request

#### What does this implement/fix?
max_depth was added as a parameter to LifelongClassificationForest and UncertaintyForest so that the max tree depth could be modified when running individual experiments to decrease run time. All relevant docstrings were updated. rotation_cifar tutorial file was also updated to test the addition of the max_depth parameter in forest.py

#### Additional information
rotation_cifar tutorial was updated for the purpose of testing the changes made to forest.py, but the tutorial itself will be simplified further in the future

### CODE REVIEW

**Review by levinwil — CHANGES_REQUESTED** [review]
Please update lines 33 and 36 in forest.py to reflect that max_depth is a parameter to those functions

**Comment by srahul1222** [comment]
@levinwil Should I also update add_task to reflect that finite_sample_correction and tree_construction_proportion are parameters as well? Also, any idea why the Travis CI build check failed?

**Comment by levinwil** [comment]
Yes please! Those updates would be great. 

To find out why Travis is failing, click on "Details" and then click on any of the red X's. You will see that it is because your changes are not black formatted. On the contribution guides, and in the slack messages, I mention that Travis will check for black formatting. For a guide on black formatting, please see https://github.com/neurodata/ProgLearn/blob/docs/docs/contributing.rst

**Comment by srahul1222** [comment]
@levinwil I made the updates you requested and formatted using black

**Review by levinwil — APPROVED** [review]

**Pull request merged**
