### PR TITLE
Fixed formatting inconsistencies in docs/experiments and docs/tutorials with jupyter black

### PR DESCRIPTION
**Pull request by kfenggg**
#### Reference issue

Consider standardizing notebook formats #413

#### Type of change

Formatting Jupyter notebooks in the docs/experiments and docs/tutorials with Jupyter black

#### What does this implement/fix?

Formatting inconsistencies in jupyter notebooks.

### CODE REVIEW

**Review by PSSF23 — CHANGES_REQUESTED** [review]
The notebooks in `docs/tutorials/` added a lot of unnecessary source codes. Are these caused by `jupyter-black`? Fix those or keep consistent with `staging` for now.

**Comment by kfenggg** [comment]
I was under the impression that main was updated as of our last meeting. I'll give this another go using the staging branch and see if we get the same issues.

**Comment by kfenggg** [comment]
@PSSF23 I redownloaded all the docs/tutorials from a newly cloned proglearn (staging branch) and reran them all with jupyter black. Looks like only one of them changed. If there are any other issues, I believe they are caused by Jupyter black.

**Review by PSSF23 — APPROVED** [review]
@kfenggg You need to have clearer commit messages.

**Pull request merged**
