### PR TITLE
Implement SPORF

### LINKED ISSUE #351: Implement SPORF in ProgLearn: fit function, recreate SPORF figures
The end goal is to create an sklearn compliant SPORF in proglearn that is modular enough to add different kinds of oblique trees in the future (i.e. MORF). This issue is in tandem with #352  

1. Implement fit function
2. Write unit tests for fit function
3. Recreate figures from SPORF paper with sklearn SPORF implementation
4. Feature request for sklearn oblique trees: write "Describe your proposed workflow" section

### PR DESCRIPTION
**Pull request by parthgvora**
#### Reference issue
Closes #351, #352.

#### Type of change
Feature request

#### What does this implement/fix?

- Scikit-learn compliant implementation of SPORF written in pure Python.
   - SPORF decision tree found in oblique_tree.py. Implements fit and predict functions as per sklearn requirements.
   - ObliqueTreeClassificationTransformer added in transformers.py
   - Unit tests for oblique_tree.py in tests/oblique_tree_test.py
- Tutorial notebook for the proglearn implementation of SPORF is provided [here.](https://github.com/parthgvora/morf_gabor_filters/blob/master/test/Proglearn_SPORF_Tutorial.ipynb) 
   - Notebook shows that proglearn SPORF produces the same results as the paper on the following UCI datasets: Hill-Valley, acute inflammation task 1, acute inflammation task 2

#### Additional information
- Feature request for scikit-learn Oblique Random Forests written [here.](https://docs.google.com/document/d/1tn3QYvupONcqbzec3LPqo48JpoCP8mMNF5L3UVC_bGY/edit)
- Code is written with modularity in mind, to allow for easy implementation of other oblique trees. For example, implementing MORF just requires implementing a new splitter class.
-  Joint work of @parthgvora and @jmandavilli, with tasks split up according to provided issues.
- @jdey4 @levinwil, please let us know if you would like to make any changes.

### CODE REVIEW

**Review by levinwil — CHANGES_REQUESTED** [review]
For oblique tree, could you please make sure all of the docstrings have underscores that match the lengths of the headers. For example, line 16 should be enough underscores to cover the "Parameters" word. Also, you shouldn't have colons after those words. 

This is to make sure things render in Sphinx correctly. Once you make those changes, can you please check the web docs to make sure things render appropriately? For reference, please check the other docs to see what it should look like and update until your docs looks like that.

**Review by levinwil — CHANGES_REQUESTED** [review]
Also, the travis tests failed. One of the reasons is you didn't include the oblique tree in the ProgLearn package. To do so, please add it to https://github.com/parthgvora/ProgLearn/blob/staging/proglearn/__init__.py

Please update the code until the travis tests pass. If the code does not pass a test, Travis will show you those errors if you check the Travis console.

**Comment by parthgvora** [comment]
Thanks for the help Will! We'll make the changes and get back to you.

**Comment by jdey4** [comment]
@parthgvora we also need all the benchmarks that show your implementation works as well as the main paper.

**Comment by parthgvora** [comment]
> @parthgvora we also need all the benchmarks that show your implementation works as well as the main paper.

This should be in the notebook - sorry for any confusion. We ran the code on 3 UCI datasets that SPORF was able to classify perfectly and also were able to classify them perfectly with our version. Notably, we could classify the Hill-Valley dataset perfectly, which RF was unable to do.

**Comment by jdey4** [comment]
I will go through it in detail. It may take time.

**Comment by parthgvora** [comment]
> I will go through it in detail. It may take time.

No problem - please let us know what you think :)

**Review by PSSF23 — CHANGES_REQUESTED** [review]
@parthgvora @jmandavilli please black format your files to pass the travis test.

**Review by PSSF23 — APPROVED** [review]

**Comment by PSSF23** [comment]
@parthgvora there were some strange indentations of docstrings, and I fixed them for you. This fix should not affect black formatting.

**Comment by levinwil** [comment]
@PSSF23 It looks good to me now. What do you think?

**Comment by PSSF23** [comment]
@levinwil Jayanta said he was going to look through the benchmarks. Otherwise, to my limit of knowledge, everything looks good.

**Review by levinwil — APPROVED** [review]

**Comment by levinwil** [comment]
@jdey4 Have you had a chance to look this over?

**Comment by jdey4** [comment]
@levinwil nope.

**Comment by levinwil** [comment]
@parthgvora Please remember to add all parameters to the docstrings

**Comment by parthgvora** [comment]
> @parthgvora Please remember to add all parameters to the docstrings

Yep, sorry! We're just going through the changes you suggested. 
We'll have docstrings and the tutorial notebooks in soon, like tonight or tomorrow. 

Thanks for your help!

**Comment by jmandavilli** [comment]
I just added the parameters to the docstrings as you suggested Will, so that should be good now. Sorry for the delay.

**Comment by levinwil** [comment]
This looks good to me. 

@jdey4 you mentioned that you wanted to go through this - have you had the chance to?

@PSSF23 do you have any comments and/or concerns? I don’t see any glaring problems.

**Comment by PSSF23** [comment]
@levinwil should the tutorials be included in the `rst` file?

**Comment by levinwil** [comment]
@PSSF23 yup!

**Comment by PSSF23** [comment]
@levinwil do you think the tutorial names should be more consistent? Like `sporf_datasets` & `sporf_decision_boundaries` or `oblique_datasets` & `oblique_decision_boundaries`?

**Comment by PSSF23** [comment]
@parthgvora @jmandavilli I added your tutorials to the `rst` file and resolved conflicts due to outdated branches. Yet as I said in the previous comment, I think more consistent names would help.

**Comment by jmandavilli** [comment]
Thank you for taking care of that @PSSF23! We can change the file names once Will confirms. Thank you guys for all of the help.

**Comment by levinwil** [comment]
I agree with @PSSF23: the tutorial names should be consistent. As for if you want the prefix to be oblique or sporf - that is up to you. I don’t have a strong opinion either way.

**Comment by levinwil** [comment]
@jmandavilli @parthgvora Have you all renamed the notebooks?

**Comment by jmandavilli** [comment]
> @jmandavilli @parthgvora Have you all renamed the notebooks?

Hey, I'm really sorry I have a final in a couple of hours. I will rename the notebooks right after

**Comment by jmandavilli** [comment]
Just renamed the notebooks, sorry for the delay. Let us know if there is anything else. Thanks again.

**Comment by jmandavilli** [comment]
Thanks for catching that Hao. My bad.

**Comment by PSSF23** [comment]
All of my concerns were addressed!

**Pull request merged**
