### PR TITLE
Added the UncertaintyForest running and analyzing tutorial

### LINKED ISSUE #95: Add tutorial for uncertainty forests
Create a python notebook demonstrating how to download, run, and use the uncertainty forest class.

### LINKED ISSUE #188: Subtask of Issue 95: Write running tutorial notebook for UncertaintyForest
See #95

### LINKED ISSUE #189: Subtask of Issue 95: Write analyzing tutorial notebook for UncertaintyForest
See #95

### PR DESCRIPTION
**Pull request by bstraus1**
Closes #188 
Closes #189 
Closes #95 

Running tutorial: demonstrates how to simply run the UF class on some data

Analyzing tutorial: recreates figure 1 to demonstrate more about the uncertainty forest class

### CODE REVIEW

**Review by levinwil — CHANGES_REQUESTED** [review]
1. Most of these functions should be defined in the docs/tutorials/functions directory 
2. There should be no pickle loading or saving
3. Please follow the file naming case conventions of the other files in the docs/tutorials directory

**Comment by bstraus1** [comment]
1. I will define the functions in that folder now
2. I only used the pickle loading because that is what is used in the original code for figure 1. I will try to remove it.
3. I will rename the files

**Comment by bstraus1** [comment]
@levinwil The changes have been made.

**Comment by levinwil** [comment]
Can you please minimize unnecessary imports in both notebooks?

**Comment by bstraus1** [comment]
Done @levinwil. Good call. There were so many unnecessary ones.

**Comment by levinwil** [comment]
Could you please remove the numpy import from the running example notebook? 

This is more for sending a new commit to the PR so we can re-run the tests - we had incorrect test settings prior to your previous PR.

**Comment by bstraus1** [comment]
Done @levinwil

**Pull request merged**
