### PR TITLE
Separated the "Tutorials" into "experiments" and "tutorials"

### LINKED ISSUE #425: Sub-issue of #423 (Match Proglearn Documentation to Verde): Add Sphinx Gallery
See #423 

This is a sub-task with the specific goal to implement a Sphinx Gallery in the proglearn documentation similar to that in the [Verde](https://www.fatiando.org/verde/latest/tutorials/overview.html) documentation.

### LINKED ISSUE #442: Sub-issue of #423 (Match Proglearn Documentation to Verde): Improve display of tutorials
See #423 

This is a sub-task with the specific goal to Improve visual display of tutorials (break up into "user guide" and "examples") in the proglearn documentation similar to that in the [Verde](https://www.fatiando.org/verde/latest/tutorials/overview.html) documentation.

### PR DESCRIPTION
**Pull request by bstraus1**
#### Reference issue
Closes #425 
Closes #442 

#### Type of change
Documentation 

#### What does this implement/fix?
This is an alternative to the original plan to add the Sphinx Gallery. The Sphinx Gallery requires re-running all of the experiments. This takes quite a long time, so this is an alternative to making the gallery. If there's a way to run the experiments in a way that would make the run-time shorter, I'd be able to still produce the Sphinx Gallery.

### CODE REVIEW

**Review by PSSF23 — COMMENTED** [review]
@bstraus1 You probably want to delete the unused function files in the tutorial folder?

**Comment by bstraus1** [comment]
I didn't want to remove any functions that might be referenced somewhere else. This is why I didn't remove any. Would you still like me to remove what I don't think is used?

**Comment by PSSF23** [comment]
They won't be referenced because you moved all the relevant notebooks.

**Review by sampan501 — APPROVED** [review]

**Comment by PSSF23** [comment]
@bstraus1 @sampan501 I will merge after the extra function files are removed.

**Comment by bstraus1** [comment]
Alrighty @PSSF23

**Pull request merged**
