### PR TITLE
Docs

### LINKED ISSUE #273: Add rst files to render docs via sphinx

### PR DESCRIPTION
**Pull request by jdey4**
#### Reference issue
closes #273 

#### Type of change
rst files added in the docs/reference/ folder for sphinx.

#### What does this implement/fix?
Renders the docs in html format.

#### Additional information
There are bugs in the docs format in several functions that need to be fixed.

### CODE REVIEW

**Review by levinwil — CHANGES_REQUESTED** [review]
Approximately half of these changes are in the wrong direction - for example, some change ProgLearn to ProgL or progressive-learning. You reverted my change to the contribution guidelines that suggest to contributors to PR into ‘staging’ and then we will PR into ‘main’. For example, we had “ The preferred workflow for contributing to `ProgLearn` is to fork the staging” which was correct. People should be forking off the staging branch. And the repo is ProgLearn, not ProgL.

You got rid of how to PR in the contribution guidelines, but we need that.

**Comment by jdey4** [comment]
I am not sure how this happened. Maybe making branch from stging somehow missed the last PR to the main.

**Comment by levinwil** [comment]
I don’t think so. The changes you suggested are changes to staging. Staging is up-to-date with main. 

It doesn’t matter too much how it happened. Those incorrect changes should be reverted before we PR into staging, however you would like to do so.

**Comment by jdey4** [comment]
Could you show me the file that has been changed?

**Comment by levinwil** [comment]
This is a feature of GitHub. There is a “files changed” tab on this very page. Click on it. Those are all the changes this PR will make to staging. Approximately half are incorrect. 

I suggest you pull from main, redo the correct changes you made (just adding Sphinx stuff) and then PR into staging.

**Comment by jdey4** [comment]
I think now it is fixed.

**Comment by levinwil** [comment]
Please see my first comment. The line in contributing.rst should be “ The preferred workflow for contributing to ProgLearn is to fork the staging” as it is on staging. 

You can either:
1. Try to revert all your incorrect changes, and we can comment back and forth and take a long time and effort 
2. Pull from main and redo your correct changes and it’ll be quicker, easier, and simpler. 

It is not fixed. Please revert all incorrect changes - I’d highly prefer you use approach 2. Let’s not create a workflow where we make a bunch of bad changes, commit those changes, then try to revert them. 

Just go back to the staging branch or main branch as it currently stands and then add the Sphinx stuff.

**Pull request closed without merging**
