### PR TITLE
Add an overview section to the ProgLearn documentation

### LINKED ISSUE #424: Sub-issue of #423 (Match Proglearn Documentation to Verde): Add Overview section
See #423 

This is a sub-task with the specific goal to implement an Overview section in the proglearn documentation similar to that in the [Verde](https://www.fatiando.org/verde/latest/tutorials/overview.html) documentation.

### PR DESCRIPTION
**Pull request by bstraus1**
#### Reference issue
Closes #424 

#### Type of change
Documentation

#### What does this implement/fix?
Add an overview section (as in the [Verde](https://www.fatiando.org/verde/latest/tutorials/overview.html) documentation)

### CODE REVIEW

**Review by PSSF23 — CHANGES_REQUESTED** [review]
@bstraus1 This change does not make sense to me. We have the overview already as the index page, so why don't you add your changes there?

**Comment by bstraus1** [comment]
@sampan501 asked for a separate overview section (that is not a landing page) and follows the format of the Verde documentation.

I agree that it has some redundancies, but also appreciate the point @sampan501 made saying that this will say the essential info not covered in the landing page.

**Comment by PSSF23** [comment]
@bstraus1 I see. Then substantial differentiation should be made. The true overview should not contain indices or badges, and the landing page would remove the "overview" terms.

I can modify them if you wish.

**Comment by bstraus1** [comment]
Sure. Or, let me know what to do. Either way works.

**Review by PSSF23 — APPROVED** [review]

**Comment by PSSF23** [comment]
@sampan501 Does the current overview satisfy your needs?

**Review by sampan501 — APPROVED** [review]

**Pull request merged**
