### PR TITLE
Update BTE definition in random_class_exp tutorial & benchmark

### PR DESCRIPTION
**Pull request by PSSF23**
#### Reference issue

Partial #345 
#### Type of change

Feature Request, Documentation
#### What does this implement/fix?

Update BTE definition in both code and text of `random_class_exp` tutorial
#### Additional information

@levinwil @jdey4

### CODE REVIEW

**Comment by PSSF23** [comment]
Added `random_class_exp` benchmark modification for #348

**Comment by levinwil** [comment]
@PSSF23 I'm thinking we close this. We could do one of two things:

1. Update all notebooks and experiments with the new BTE/FTE definition, which would take a while and require re-runs.

2. Keep them all as-is. 

What do you think?

**Comment by PSSF23** [comment]
@levinwil I am fine with either way, as long as all benchmarks/tutorials have consistent FTE/BTE definitions.

I can open another PR to fix the netlify display for equations if you want.

**Comment by levinwil** [comment]
@PSSF23 yes please! That would be great!

**Pull request closed without merging**
