### PR TITLE
spoken_digit experiment tutorial with L2F and L2N

### PR DESCRIPTION
**Pull request by chenyugoal**
#### Reference issue

#48 
Run progressive learning on non-image tasks. 
Here I used an audio dataset.
#### Type of change

Added a new experiment for progressive learning in Jupyter notebook, with explanation step by step.
So it can also be treated as a tutorial.
#### What does this implement/fix?

Two algorithms, L2N and L2F, are offered as options to choose from.

#### Additional information

The 'shuffle task' option is offered and discussed at the end of the notebook, to show the intrinsic trend of progressive learning with 'noise' canceled out.

### CODE REVIEW

**Review by PSSF23 — COMMENTED** [review]
@chenyugoal I think you need to make sure the BTE equation is displayed correctly. You can check out the markdown codes [here](https://github.com/neurodata/ProgLearn/blob/main/docs/tutorials/xor_nxor_exp.ipynb)

**Comment by chenyugoal** [comment]
> @chenyugoal I think you need to make sure the BTE equation is displayed correctly. You can check out the markdown codes [here](https://github.com/neurodata/ProgLearn/blob/main/docs/tutorials/xor_nxor_exp.ipynb)

**Comment by chenyugoal** [comment]
@PSSF23 Hi, Haoyin! Thank you for your review!
I used the updated BTE/TE/FTE equation from the new paper, in which we divide the expectation of Error1 by the expectation of Error2. But in fact, the coding is exactly the same.

**Comment by chenyugoal** [comment]
@PSSF23 Thank you for your review. I have confirmed with @jdey4 and @levinwil . The BTE/FTE should be the ratio of expectations, rather than the expectation of ratios (the one appears in the paper titled A general approach to progressive learning).

**Comment by PSSF23** [comment]
@chenyugoal sorry I couldn't fully fix your equation display issue. It might involve some unrecognized characters. Please resolve it before merging.

As for the TE definitions, there has been some back-and-forth discussions and we decided to keep current tutorials as they are for now. The important thing is that your **implementation** corresponds to your **equations**.

**Comment by PSSF23** [comment]
@chenyugoal also, mathematically "the ratio of expectations" and "the expectation of ratios" are the same. The thing we were debating is how the implementation should be: "average first then take ratios" or "take ratios first then average."

Which implementation did you use?

**Comment by chenyugoal** [comment]
@PSSF23 I first average the accuracies (from all repetitions), then use the averaged accuracy to compute ratios, i.e. BTE/FTE/TE.

**Comment by levinwil** [comment]
@PSSF23 its not true that the ratio of expectations and the expectation of ratios are mathematically the same. Ratio of expectations is E[R_single_task]/E[R_multitask] while expectation of ratios is E[R_single_task/R_multitask]. It’s kinda a moot point though since I think Chenyo did ratio of expectations, which is the correct definition. 

I think this looks good. @PSSF23 do you see any edits you’d like made?

**Comment by chenyugoal** [comment]
@PSSF23 I found that when opening .ipynb on [GitHub](https://github.com/chenyugoal/ProgLearn/blob/staging/benchmarks/spoken_digit_exp/spoken_digit_exp.ipynb), some of the equations are hidden. But in [nbviewer](https://nbviewer.jupyter.org/github/chenyugoal/ProgLearn/blob/staging/benchmarks/spoken_digit_exp/spoken_digit_exp.ipynb), they look fine, from my side.

**Comment by PSSF23** [comment]
@levinwil the expectation of ratios should be E[R_(single_task/multitask)] I believe? Then that will be different mathematically, while your two equations are still the same thing (E[A/B] = E[A]/E[B]). Anyway as long as the implementation is correct I have no complain.

@chenyugoal I think we want to make sure it's displayed correctly everywhere. Maybe try separate the 3 equations with descriptions about each one?

**Comment by chenyugoal** [comment]
@PSSF23  Good point! And it works. Now it displays correctly, link here [Github](https://github.com/chenyugoal/ProgLearn/blob/staging/benchmarks/spoken_digit_exp/spoken_digit_exp.ipynb).

**Review by PSSF23 — APPROVED** [review]
@chenyugoal great!

**Comment by levinwil** [comment]
@PSSF23 by the way, the following statement is false:

E[A/B] = E[A]/E[B]

As an example, suppose A takes on values a_1 and a_2 and B takes on values b_1 and b_2. The left side of the above equation is (a_1/b_1 + a_2/b_2)/2. The right side of the above equation is ((a_1 + a_2)/2)/((b_1 + b_2)/2). The expectation of the division of two random variables can get pretty complicated mathematically. If b were a constant, you could simply pull that out front, and you get the same equation above. But when B is a random variable, it gets more complicated. Numerically, you also get different results doing the radio of averages and the average of ratios. Regardless, Chenyu did the right calculations so we’re all good.

**Pull request merged**
