### PR TITLE
Spiral Experiment tutorial (and associated functions file) added

### LINKED ISSUE #370: Creating spiral experiment tutorial
Using the code [here](https://github.com/neurodata/ProgLearn/tree/main/benchmarks/xor_rxor_spiral_exp) (in the benchmarks folder) to create a step by step tutorial recreating the spiral experiment.

### PR DESCRIPTION
**Pull request by bstraus1**
#### Reference issue
Closes #370 

#### What does this implement/fix?
Added Spiral Experiment tutorial (and associated functions file)

### CODE REVIEW

**Review by PSSF23 — COMMENTED** [review]
@bstraus1 I added your tutorial to the index file so it will show up in the Netlify preview. And would you want to add more subtitles to your tutorial for easier navigation? The "for Progressive Learning" part in the title seems redundant, too.

**Comment by PSSF23** [comment]
@bstraus1 Also as a reminder, try not to make any direct changes to the `main` and `staging` branches, even on your fork. Those branches are supposed to be updated and be the same as parent repo when needed.

**Comment by bstraus1** [comment]
@PSSF23 Is the correct process to create my own branch, pull from staging, then merge into staging?

**Comment by PSSF23** [comment]
@bstraus1 Generally yes. And we can branch off from our forked and updated staging to avoid the extra pulling.

**Comment by bstraus1** [comment]
@PSSF23 How's that?

**Review by PSSF23 — APPROVED** [review]
@bstraus1 Looks great to me! And you have presented the results I believe?

**Comment by bstraus1** [comment]
@PSSF23 Yep. And they match Jayanta's results [here](https://github.com/neurodata/ProgLearn/blob/main/benchmarks/spiral_experiment/plots/spiral_plot.pdf)

**Pull request merged**
