### PR TITLE
ConvRF Experiments

### PR DESCRIPTION
**Pull request by ypeng22**
#### Reference issue
Issue #99 Convolutional Forests

#### Type of change
Experiments and Kappa plots for ConvRF

#### Additional information
The experiments really can't be simplified much more. This is not a tutorial but there is really no place for it but Jovo wants it in ProgLearn so this was the directory by elimination. You can't simplify the code by putting stuff into functions or else you'd be passing huge amounts of data around.

### CODE REVIEW

**Review by PSSF23 — COMMENTED** [review]
@ypeng22 No result files, please. Tutorials should be self-contained.

**Comment by PSSF23** [comment]
@ypeng22 I removed a function in your function file because it was defined again in your tutorial and thus never used. But I believe your notebook needs some huge optimizations.

**Comment by PSSF23** [comment]
My suggestion of file organization (the files needed for this PR) is:

- `tutorials/functions/ConvRF.py`
- `tutorials/ConvRF_Kappas.ipynb`

That's all. As your notebook does not use `ProgLearn`, it would not be included in the `rst` file.

**Comment by levinwil** [comment]
@ypeng22 Please do not save out the results into CSV files. Please write them directly to variables in the notebooks/python files.

**Comment by ypeng22** [comment]
@PSSF23 I have fixed the issues, can you review it please?

**Comment by PSSF23** [comment]
@ypeng22 first I reformatted your function file with `black` so that part of the problem is solved. Second, I would not call it a fix as long as all those "here" statements remain in your notebook. Please follow the [tutorial guideline](https://github.com/neurodata/ProgLearn/blob/staging/docs/contributing.rst#tutorial-guidelines).

**Comment by PSSF23** [comment]
@ypeng22 as for more next-step suggestions, I believe the codes you use for the last three graphs are highly identical and could be made into one local function. And do you need to show the graphs for all intermediate steps?

**Review by PSSF23 — APPROVED** [review]
@levinwil as this highly complex notebook is more like an experiment instead of a tutorial, I would suggest some leniency towards its formatting. How do you think of its current version?

**Comment by levinwil** [comment]
Yeah I agree - this isn't quite a tutorial, nor is it an experiment. I think it should lie where it is, formatted as is (or close to as is, but perhaps slightly simpler).

**Pull request merged**
