### PR TITLE
Changed headers to be more descriptive for online display

### PR DESCRIPTION
**Pull request by bstraus1**
#### Reference issue
References #356 

#### Type of change
Documentation / Organization Change

#### What does this implement/fix?
Changed headers to be more descriptive for online display

### CODE REVIEW

**Review by PSSF23 — COMMENTED** [review]
If you check the [website preview](https://deploy-preview-358--neurodata-proglearn.netlify.app/tutorials/uncertaintyforest_fig1.html), you will see that some `subtitles` in the Uncertainty Forest tutorials are falsely recognized as `titles`, including:

- "Analyzing the UncertaintyForest Class by Reproducing Figure 1" in "Uncertainty Forest Figure 1 Tutorial"
- "Simply Running the Uncertainty Forest class" in "Uncertainty Forest: How to Run Tutorial"

The way to keep one single entry for each tutorial is to have **only one line** marked with "#" at front. The menu organization might cause confusion otherwise.

**Comment by bstraus1** [comment]
Does that look better? @PSSF23

**Review by PSSF23 — COMMENTED** [review]
@bstraus1 Looks good to me! Don't know where the conflict exists though.

**Comment by PSSF23** [comment]
@bstraus1 Please resolve the merging conflict or the travis test would not run.

**Comment by bstraus1** [comment]
@PSSF23 I cannot resolve the conflict since I do not have write access to this repository. It looks like the difference is just a version number.

**Comment by levinwil** [comment]
@bstraus1 you can resolve the conflict by manually changing the file. Simply change your notebook (the raw file rather than the Jupyter notebook HTML display of it) to match the version on staging. 

A way around this issue in the future: always pull from and push to staging, as mentioned in the contribution guidelines.

**Comment by bstraus1** [comment]
@levinwil @PSSF23 Looks good now.

**Review by levinwil — APPROVED** [review]

**Pull request merged**
