### PR TITLE
ISIC Scene Segmentation with Proglearn NN

### PR DESCRIPTION
**Pull request by KhelmholtzR**
#### Reference issue
#39 

#### Type of change
Performed a scene segmentation experiment using ProgLearn with a Unet neural network backbone.

#### What does this implement/fix?
Performed a scene segmentation experiment using ProgLearn with a Unet neural network backbone in a Jupyter notebook. Made adjustments to the transformers class to work with multi-dimensional outputs. Created the MLKNNClassification voter class to create a voter for multi-dimensional outputs (credit to @nhwagle). Created a new decider to work with the outputs of the MLKNNClassification voter.

### CODE REVIEW

**Comment by jdey4** [comment]
Please fix the CI issues by changing requirement.txt to have additional packages used in the source code
Screen Shot 2022-05-11 at 10 37 24 PM
.

**Comment by jdey4** [comment]
Also, please explain the experiment setup and evaluation criteria in details. You can see this one: https://github.com/neurodata/ProgLearn/blob/main/docs/experiments/fte_bte_mnist.ipynb. And it is not a tutorial. It should be in the experiments.

**Comment by jdey4** [comment]
@KhelmholtzR you need to add unit test. The code coverage is dropping. That's why we can't merge it.

**Comment by jdey4** [comment]
@KhelmholtzR you need more code coverage or you can ignore unit testing for your certain portion of the codes using this: https://coverage.readthedocs.io/en/6.3.1/excluding.html

**Comment by KhelmholtzR** [comment]
Seems like codecov is complaining about uncovered lines in the original file that git diff sees as being deleted and readded and that's what's causing the check to fail. What should I do?

**Comment by jdey4** [comment]
@KhelmholtzR Write a unit test that checks the whole process. Fit a proglearn class using something known, like use an array of ones as X and put 1 as label. Use other samples as 0 as X and put 0 as label. See the result. You should get 100% accuracy if your implementation is correct.

**Review by jdey4 — APPROVED** [review]

**Pull request merged**
