### PR TITLE
Added API reference

### LINKED ISSUE #448: Sub-issue of #423 (Match Proglearn Documentation to Verde): Add API Reference
See #423 

This is a sub-task with the specific goal to add the API reference section in the proglearn documentation similar to that in the [Verde](https://www.fatiando.org/verde/latest/tutorials/overview.html) documentation.

### PR DESCRIPTION
**Pull request by bstraus1**
#### Reference issue
Closes #448 

#### Type of change
Added API reference to the Proglearn documentation

### CODE REVIEW

**Review by PSSF23 — COMMENTED** [review]
@bstraus1 First you need to black format your files to pass the test. That's simple.

Second is about the api page. Would you consider reordering the references and link the two sims to their respective spots? The current order of voter/decider/forest/network/transformer does not make sense to me, and the page itself should not show any function contents.

**Comment by bstraus1** [comment]
I will black format the code.

Regarding the order, I can definitely switch that. What would make more sense to you?

Regarding the function contents, that's an issue that I've been working with Sambit about. I haven't found a way to hide those. The best alternative now (unless you have any idea about how to fix the Sphinx generation) is to return to the current documentation page, which doesn't contain much documentation at all.

**Review by PSSF23 — COMMENTED** [review]
I made a small change that I think will do the trick. Let's see how the results turn out in preview.

**Review by PSSF23 — COMMENTED** [review]
@bstraus1 Okay I suppose it's not so easily solved as a typo. Though my knowledge of Sphinx is not sufficient, but perhaps another layer should be made for the `proglearn.sims` module. Or removing the sims would also do? Let me know when you and sampan reached a decision~

**Comment by sampan501** [comment]
I'm going to wait to review until everything looks right. Looking at it now, ``API Reference`` is not displaying properly and ``Reference`` needs to be removed

**Comment by bstraus1** [comment]
@PSSF23 I've now black formatted and fixed the visual issues. I think it should be good (but will wait on the preview).

**Comment by bstraus1** [comment]
Yeah I think it looks good.

**Review by PSSF23 — COMMENTED** [review]
@bstraus1 You still need to black format `progressive_learner.py`.

**Review by PSSF23 — COMMENTED** [review]
The API page looks good, but the order still doesn't make sense to me. How about:

- transformers
- voters
- deciders
- progressive_learners
- forest
- network

**Comment by bstraus1** [comment]
@PSSF23 How does it look? (I've changed the order to the more logical progression you suggested)

**Review by PSSF23 — APPROVED** [review]
@bstraus1 Not bad. Now all you need is black formatting.

@sampan501 How do you think?

**Comment by bstraus1** [comment]
I did run black on this. Does it not look right? @PSSF23

**Comment by sampan501** [comment]
I think it looks great!

@bstraus1 Check the CircleCI logs, clearly some black formatting issues

**Comment by PSSF23** [comment]
@bstraus1 No you didn't.

> @bstraus1 You still need to black format `progressive_learner.py`.

**Comment by bstraus1** [comment]
Should be fixed now.

**Pull request merged**
