### PR TITLE
ENH Add streaming functionality to Synergistic Forest

### PR DESCRIPTION
**Pull request by nhahn7**
#### Reference issue

#34 #501 
#### Type of change

Feature Request

#### What does this implement/fix?

Add streaming functionality for  forests with `update_task` function.

#### Additional information

- For streaming Synergistic Forests, using `update_task` requires partial fitting from [scikit-learn-stream](https://github.com/PSSF23/scikit-learn-stream/tree/stream) fork

- [Notebook demonstrating SynF vs DF (streaming and batch)](https://nbviewer.org/github/nhahn7/ProgLearn_2021-2022/blob/main/Nick-Hahn/NDD_II/Week_8/batch_vs_streaming_synf.ipynb)

- Extended from #526 #528

### CODE REVIEW

**Review by PSSF23 — COMMENTED** [review]
Remember to remove the extra `print` statements~

**Review by PSSF23 — CHANGES_REQUESTED** [review]
`black` formatting is not complete.

**Review by PSSF23 — COMMENTED** [review]
You can add unit tests to fix the `codecov` issue. Also, replicate the change in 9aaa570 to solve the website rendering.

**Review by PSSF23 — COMMENTED** [review]
@nhahn7 you can include the XOR experiments in this PR. Or you can open another one for those.

**Comment by nhahn7** [comment]
@PSSF23 Sounds good, I’ll work on adding unit tests and remove the `network.py` changes today. For the XOR experiments, the notebook currently is just used for plotting (not generating the results). Should I make it in to a tutorial of how to use `update_task`? Or leave it as is where it just plots from existing results in .txt files?

**Comment by nhahn7** [comment]
@PSSF23 It looks like its failing due to not recognizing the `partial_fit` function from sci-kit learn fork. Can this be resolved with changing `requirements.txt` to specify https://github.com/PSSF23/scikit-learn-stream instead of scikit-learn>=0.22.0?

**Review by PSSF23 — COMMENTED** [review]
@nhahn7 That would be too much of a dependency. Instead, we can state that the feature is experimental & modify the CircleCI checks.

**Review by PSSF23 — COMMENTED** [review]
If `classes` is not currently defined as a variable, I would prefer to have the same name for all `classes` and `input_classes`.

**Review by PSSF23 — CHANGES_REQUESTED** [review]
Update your CircleCI cache from `v2` to `v3` to resolve the error.

**Review by PSSF23 — CHANGES_REQUESTED** [review]
As currently there's no way to pass the `partial_fit` test, just comment out the test for now.

The notebooks and functions should be in `experiments`. And you did not add the notebook to the `rst` list.

**Pull request merged**
