### PR TITLE
Adding Notebooks showing adversarial regression

### PR DESCRIPTION
**Pull request by latasianguy**
#### Reference issue

Part of Issue #5 

#### Type of change

Adding Jupyter notebooks with experiments.

#### What does this implement/fix?

Showing some initial experiments to verify that adversarial transformers are a problem in the regression setting.

### CODE REVIEW

**Comment by latasianguy** [comment]
@levinwil let me know if I need to update the comments or if this initial commit is good enough

**Review by PSSF23 — COMMENTED** [review]
I don't think the `proglearn.egg-info` folder should be uploaded at all...

**Comment by PSSF23** [comment]
@latasianguy I think you can delete the entire folder~

**Review by levinwil — APPROVED** [review]

**Comment by levinwil** [comment]
@latasianguy can you please delete the egg folder and PR that into staging?

**Pull request merged**
