### PR TITLE
Bayes' Error Estimation for Gaussian Parity

### LINKED ISSUE #510: Adding Bayes' Error Calculation for Gaussian Sparse Parity
The Bayes' Error is the minimum error that any algorithm can achieve, because this is an error that is inherent in the problem. While creating algorithms (including ProgLearn) that work with Gaussian Sparse Parity problems, it is imperative to have an estimate of what the actual inherent error of this problem is. This will help identify bugs in code, as well as provide a realistic estimate of how well the algorithm can be expected to perform. 

#### Additional context
In order to resolve this requirement, I intend to create a simple analytical and numerical derivation of the Bayes' error found. This would step through the Gaussian Sparse Parity code, thus additionally providing a tutorial-like foundation for the problem as well as its inherent error. 

This is a standalone implementation, which can be utilized for any other algorithm that is tackling the Gaussian Sparse Parity problem.

### PR DESCRIPTION
**Pull request by AishwaryaSeth**
#### Reference issue

Close #510 

#### Type of change

Tutorial added 

#### What does this implement/fix?

Added Jupyter Notebook which traces the Bayes' error estimate for the Gaussian Parity problem. 
Analytical steps are mentioned, and the final estimation is done by a numeric estimation.

#### Additional information

This is a standalone notebook, and can be used for different projects as it focuses on calculation of Bayes' Error for the Gaussian XOR problem only.

### CODE REVIEW

**Review by PSSF23 — COMMENTED** [review]
Looks good. Can be made better by referring to: https://proglearn.neurodata.io/contributing.html#tutorial-guidelines

Also, create an issue to describe what you are trying to accomplish.

**Comment by AishwaryaSeth** [comment]
Hi, 

As per your comments @PSSF23, I have followed the given guidelines and shifted the support functions to a separate file, and added the markdown comments so that it will appear in the menus. I have also opened a corresponding issue with a description of what I intended to do. The issue is now marked in the pull request. 

As per my discussion in class today with @jdey4, I have not shifted most of the key functions to the separate function file. This is because the intention of this tutorial is to step through the creation of the gaussians as well as the calculation of the Bayes' error. By including the long form of the functions within the notebook, it becomes more tutorial-like and instructive to all those who refer to it in the future. 

Please do let me know if any further changes/updates are required. 

Thanks!

**Review by PSSF23 — COMMENTED** [review]
You forgot one part which is adding the tutorial to `netlify`. Review the website preview when the checks finish.

**Comment by AishwaryaSeth** [comment]
Hi @PSSF23, 

Apologies for missing that. I've adjusted the formatting and now it renders correctly in Netlify. 

Please have a look and let me know if there's anything else!

Thanks for your help.

**Review by PSSF23 — APPROVED** [review]
@AishwaryaSeth I removed the contact info as we want people to contact @neurodata when things go wrong in the future. Also the notebook was not black formatted. There's something wrong with the checks, which I will fix later.

**Comment by AishwaryaSeth** [comment]
@PSSF23 okay great, thanks for letting me know. I should definitely set up Black for my VSCode and Jupyter then, to prevent these hand-formatting issues in the future. 

What would be the best way to raise a general PR then?

**Comment by PSSF23** [comment]
Our CircleCI tests should check for the code style we want. What do you mean by **general**?

**Comment by AishwaryaSeth** [comment]
Would the CircleCI tests also make those minor adjustments to the formatting? 

Whenever I raise a PR to staging of a project, is it better to do so from a separate branch within the same project, or from my own profile (like I did here), or is there another better practice to follow for the same? 

Also, you're right, my repo shows that I'm still 30 commits ahead of the neurodata:staging after you've merged my commit. How do I resolve this?

**Comment by PSSF23** [comment]
CircleCI would ask you to make the adjustments.

https://proglearn.neurodata.io/contributing.html#contributing-code

You can refer to [this post](https://gist.github.com/glennblock/1974465#gistcomment-2245163) to resolve the syncing issue. Your changes have been incorporated.

**Pull request merged**
