### PR TITLE
Figures of spoken_digit_experiment and Optimization of the notebook

### PR DESCRIPTION
**Pull request by chenyugoal**
@jdey4 Could you please take a look?

#### Reference issue

#388 
#### Type of change

supplementary content
#### What does this implement/fix?

1. remove redundant code in Jupyter notebook.
2. run 200 repetitions for each experiment and save results in .npy.
3. generate figures following the template code provided by Jayanta.
#### Additional information

Probably helpful for issue #434 @mkusman1

### CODE REVIEW

**Review by PSSF23 — COMMENTED** [review]
My opinion is that cache and figures should not be included, as they will be generated whenever the notebook is run again. @jdey4 how do you think?

**Comment by jdey4** [comment]
@PSSF23 it is in the benchmark. It will not render in the tutorial. We can approve it, I guess.

**Comment by PSSF23** [comment]
Figures are alright then, but not cache in my opinion. None of the current benchmarks include cache.

**Comment by jdey4** [comment]
@chenyugoal I am currently fixing the experiment. I saw some bugs. I will commit the correction.

**Comment by chenyugoal** [comment]
OK, I revert the commit. @jdey4

**Comment by chenyugoal** [comment]
The calculate_results() function might be really opaque to someone else than me. DM me if you need help. @jdey4

**Comment by PSSF23** [comment]
@chenyugoal as @jdey4 is committing fixes, your cache and figures have become all obsolete. I advise deleting them all and let Jayanta decide what to upload after running the fixed version.

**Comment by jdey4** [comment]
@chenyugoal could you give me write access to your fork?

**Comment by chenyugoal** [comment]
@PSSF23 could you approve the PR? Jayanta and I have fixed the bugs in the experiment. And unnecessary caches are all removed now. Only one figure used in Jayanta's manuscript is kept, namely language.pdf.

**Review by PSSF23 — APPROVED** [review]

**Pull request merged**
