### PR TITLE
binning exps (draft)

### PR DESCRIPTION
**Pull request by p-teng**
#### Reference issue
#33 add binning capabilities

#### Type of change
Binning function added in binning.py, some experiments comparing performance with varying bin size

#### What does this implement/fix?
- Adds binning capabilities to repo
- Notebooks with binning experiments for label shuffle, random class, and sample size experiments

#### Additional information
Still a work in progress - need to add time measuring to experiments, as well as add more functionality and visualizations

### CODE REVIEW

**Comment by PSSF23** [comment]
@p-teng I know this PR is still a draft, but are you trying to replicate all the base experiments with binning added? I noticed that some function files like `rotation_cifar` have no corresponding notebooks, so will you add them as well?

@jdey4 @levinwil Do you have comments on file organization?

**Comment by levinwil** [comment]
This file structure is wrong. All of your stuff should be under docs/tutorials. And you should not duplicate files that already exist in that folder. You should simply be adding the binning experiment files to docs/tutorials - notebooks under that directory and .py files under ‘functions’, just like every other tutorial

**Review by PSSF23 — CHANGES_REQUESTED** [review]
@p-teng if I understand correctly, the function files for tutorials are completely unchanged. So you would not need to replicate them, and the file structure suggested by @levinwil would be something like such:

- `docs/tutorials/functions/binning.py`
- `docs/tutorials/<original names>_binning.ipynb`

@levinwil do you think the binning notebooks should go into the `rst` file? My opinion is probably "no" at this point.

**Comment by levinwil** [comment]
I completely agree with @PSSF23 on file structure and exclusion from the ‘rst’ file

**Comment by p-teng** [comment]
Thanks for the feedback - will modify the file structure. One question - for some of these experiments it's difficult to add binning without modifying the function files, for example the sample_size experiment can't be binned without modifying the test_suite function. How should I proceed in these cases?

**Comment by PSSF23** [comment]
@p-teng have you been specifically instructed to add binning to that experiment? I ask so because that tutorial is not directly related to `proglearn`, so you might want to exclude it.

**Comment by p-teng** [comment]
@PSSF23 I haven't been specifically instructed to add to any particular experiment, should I just add binning for experiments that don't need their functions modified?

**Comment by PSSF23** [comment]
@p-teng that will be a great start!

**Comment by p-teng** [comment]
TODO:
Implement optimal binning algorithm for discrete, continuous, and multi-class binning as in this paper: https://arxiv.org/abs/2001.08025
More complete binning experiments with benchmark comparisons
Improved file structure

**Pull request closed without merging**
