### PR TITLE
Added travis auto PyPi upload on change to main

### LINKED ISSUE #308: set up CI to auto push main to pypi

### PR DESCRIPTION
**Pull request by levinwil**
#### Reference issue

Closes #308 

#### Type of change

Feature Request

#### What does this implement/fix?

Updates the travis deployment such that Travis uploads the latest version of our repo to PyPi upon a modification to main

### CODE REVIEW

**Comment by jdey4** [comment]
Should there be a place where we describe the version?

**Comment by levinwil** [comment]
I think it updates automatically, but I could be wrong.

**Comment by jdey4** [comment]
See line 21 here: https://github.com/neurodata/hyppo/blob/master/setup.py

**Comment by levinwil** [comment]
@jdey4 Just added the updates to follow hyppo - we will have to manually update the version number in proglearn/__init__.py. Sambit said they do the manual updating for hyppo.

**Review by jdey4 — APPROVED** [review]

**Pull request merged**
