### PR TITLE
Make Jupyter notebook showing the capability of progressive-learning on the food-101 dataset

### PR DESCRIPTION
**Pull request by srahul1222**
#### Reference issue
Closes Issue #40 

#### Type of change
Feature Request

#### What does this implement/fix?
Runs the BTE/FTE/TE experiment on the food-101 dataset using the LifelongClassificationForest. The food-101 dataset, containing 101000 images of foods, is much larger than the CIFAR dataset used in the benchmark test. The jupyter notebook includes information on how to acquire and load the dataset as well as the experiment itself, referencing code contained in a separate 'functions' folder. The 'results' folder contains a figure, like the one from the progressive learning paper, that plots BTE, FTE, TE, and accuracy for this dataset.

#### Additional information
Merging this PR completes Sprint 1 for NDD

### CODE REVIEW

**Comment by levinwil** [comment]
1. This should just be a notebook, not in a folder. It should be just like the other tutorial notebooks.
2. Please don't print so many statements. 
3. You should be outputting FTE and BTE and TE and accuracies, just like every other dataset.

**Review by PSSF23 — COMMENTED** [review]
@srahul1222 as Will mentioned, the notebook should be self-contained with its function file in the `tutorials/functions` folder and output no files.

So the files added would be:

- `tutorials/fte_bte_food101.ipynb`
- `tutorials/functions/fte_bte_food101_functions.py`

Also, please add your tutorial name to `tutorial.rst`.

**Comment by PSSF23** [comment]
@levinwil Is this PR enough to close #40?

**Comment by PSSF23** [comment]
@srahul1222 your notebook still produce files like `food_101_array_data_x_*.npz`, which is not expected of tutorial formats. Please read the tutorial guideline and exclude any file outputs.

Also, I think your data initialization code blocks could be compressed into one function repeated 10 times. And I see no necessity or reason to cut them apart and then concatenate together.

**Comment by levinwil** [comment]
@PSSF23 Even after those fixes, I have no idea if this notebook is sufficient to close #40. I think that is up to @jovo - jovo, do you have any thoughts?

**Comment by jovo** [comment]
seems adequate to me.
it would be better if it also compared PLN, and the other algorithms.

On Fri, Dec 11, 2020 at 9:37 AM Will LeVine <notifications@github.com>
wrote:

>
> *      External Email - Use Caution      *
>
>
>
> @PSSF23
> <https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FPSSF23&data=04%7C01%7Cjovo%40jhu.edu%7C07afabbc6baa4806be1208d89de23d8a%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637432942300520004%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Z5X9yO0wM6oA%2F1Gy57LmXpE9czV2AXkNFIYav3HGPd8%3D&reserved=0>
> Even after those fixes, I have no idea if this notebook is sufficient to
> close #40
> <https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fneurodata%2FProgLearn%2Fissues%2F40&data=04%7C01%7Cjovo%40jhu.edu%7C07afabbc6baa4806be1208d89de23d8a%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637432942300524998%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=WVT7VVJNMEPqbEG5mACZw7NCX9Bn9xsSXPnQPCJ9aYo%3D&reserved=0>.
> I think that is up to @jovo
> <https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjovo&data=04%7C01%7Cjovo%40jhu.edu%7C07afabbc6baa4806be1208d89de23d8a%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637432942300529985%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=xDFQNQV9iBVsPw9FQ9TQym31QibQoK4fMVp2mFkgGqU%3D&reserved=0>
> - jovo, do you have any thoughts?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fneurodata%2FProgLearn%2Fpull%2F390%23issuecomment-743228209&data=04%7C01%7Cjovo%40jhu.edu%7C07afabbc6baa4806be1208d89de23d8a%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637432942300534977%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=rS7iU5o0zIuH76DtW3xQU09S8KbxO20b36o8m7o%2F0sk%3D&reserved=0>,
> or unsubscribe
> <https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAAKG4W52IDMHHL24KZU2PLSUIVBHANCNFSM4UV2H5FQ&data=04%7C01%7Cjovo%40jhu.edu%7C07afabbc6baa4806be1208d89de23d8a%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C637432942300539969%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=jd9l9dFsc4fxkowhnTZ2q6B5ZBorAiT5B%2FH4CwKP2ao%3D&reserved=0>
> .
>


-- 
With gratitude,

Joshua T Vogelstein, PhD
neurodata.io | BME@JHU <https://www.bme.jhu.edu/> | dA/dt > 0 > dJ/dt
<https://twitter.com/neuro_data/status/1279067902658916352>
where A = appreciating, J = judging, and t = time.
How can I do better? <https://forms.gle/iEad8byD89eTPdYx6>

**Comment by srahul1222** [comment]
> Also, I think your data initialization code blocks could be compressed into one function repeated 10 times. And I see no necessity or reason to cut them apart and then concatenate together.

@PSSF23 I combined all the individual code blocks into one loop as requested. As for why I split the data into 10 batches and then concatenated, when I tried parsing through all the data at once and adding it to a numpy array, I kept running into a memory error where it said "The kernel has died". I found that splitting it up then concatenating avoided this error and made it faster.

**Comment by PSSF23** [comment]
@srahul1222 I moved the tutorial index after the installation guide, which should always remain on top. Other than that everything looks pretty good to me.

@levinwil Do you think the condensed tutorial is good enough?

**Comment by levinwil** [comment]
@srahul1222 why are some of the cells in the notebook not run? How did you plot the final result if you never ran the cells that define the variables you are plotting?

**Comment by srahul1222** [comment]
@levinwil After deleting the print statements as you asked for earlier, I didn't run it again but instead just clicked "Restart and Clear Output". The plot of the final results shown is the same plot from before I restarted the kernel.

**Comment by PSSF23** [comment]
@srahul1222 in case of past changes and @levinwil's concern, I recommend that you re-run everything with the new notebook and resolve potential errors.

**Comment by srahul1222** [comment]
@PSSF23 I didn't re-run the notebook after submitting the PR because it takes several days to run on my laptop. I do now have an account on synaptomes1.neurodata.io, so I could run the code on the cluster, but I have had some trouble setting it up and need help with that. What would you recommend I do?

**Comment by PSSF23** [comment]
@srahul1222 running some smaller datasets to test the codes? I have no idea about how to use virtual machines on that website.

**Comment by srahul1222** [comment]
@PSSF23 Ok I can do that. I'll test the code on just the first 3 tasks (30 classes total) of this dataset

**Comment by srahul1222** [comment]
@PSSF23 I ran the code on just the first 30000 images and got it to work, as shown in this [notebook](https://github.com/srahul1222/progressive-learning/blob/my-feature/docs/tutorials/fte_bte_food101_3tasks.ipynb). I also made 3 small changes to the notebook where I fixed inconsistencies in variable naming.

**Review by PSSF23 — APPROVED** [review]
@srahul1222 great!

@levinwil do you have other suggestions?

**Pull request merged**
