### PR TITLE
consolidate all experiments for KNNRegression and KNNClassification

### PR DESCRIPTION
**Pull request by latasianguy**
#### Reference issue

- Part of #5 , combining regression (and classification) experiments to staging

#### Type of change

- Feature request, showcasing experiments on KNNDeciders when faced with adversarial data

#### What does this implement/fix?

- add experiments into separate folders in tutorial
- add KNNRegressionDecider and KNNClassificationDecider to deciders.py
- black format deciders.py
- keep everything on staging and not on different branches

#### Additional information

N/A

### CODE REVIEW

**Comment by latasianguy** [comment]
@levinwil let me know if anything needs to be changed

**Comment by levinwil** [comment]
@latasianguy You should not be merging into staging. You should just make a new branch called `KNNDecider` and commit directly to it.

**Comment by levinwil** [comment]
Closing, since this should be merged into a main branch called `KNNDecider`

**Comment by PSSF23** [comment]
Reopen and redirect to `KNNDecider` branch

**Pull request merged**
