### PR TITLE
ConvRF Experiments

### PR DESCRIPTION
**Pull request by ypeng22**
#### Reference issue
Issue #99 - Convolutional forests

#### Type of change
Add new class files and jupyter notebooks.

#### Additional information
Experiments and plots of 45 cifar 2-class classification tasks.

### CODE REVIEW

**Review by PSSF23 — COMMENTED** [review]
@ypeng22 is this PR related to #231? Or does it close #99?

Also some minor suggestions for file names: Maybe you can name the class file `ConvRF.py` to avoid the confusing `ConvRFClassifier.ConvRFClassifier(*)` syntax? Then more classes like `ConvRFRegressor` could be added to it in the future.

**Comment by ypeng22** [comment]
@PSSF23 sounds good, changed the name.

**Comment by PSSF23** [comment]
@ypeng22 don't forget to change the syntaxes in the benchmark as well!

**Comment by ypeng22** [comment]
My bad, rookie mistake.

**Comment by ypeng22** [comment]
@jdey4 are you fine with a new folder for convolutional forests in /benchmarks? Will directed me to jovo who directed me to you.

**Comment by levinwil** [comment]
@ypeng22 after some thought, I strongly believe this should go in docs/tutorials. Not benchmarks.

**Comment by ypeng22** [comment]
@levinwil Ok, I will add in more documentation and move it then.

**Comment by levinwil** [comment]
Great. Thanks!

**Pull request closed without merging**
