### PR TITLE
fig fixed

### LINKED ISSUE #337: Fix spiral and xor figure according to the decision in ProgLearn meeting.
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context (e.g. screenshots)**

### PR DESCRIPTION
**Pull request by jdey4**
#### Reference issue

This closes #337

### CODE REVIEW

**Comment by levinwil** [comment]
1. It’s supposed to be Random Forest, not naive forest.
2. For the middle top plot, please show the lines for x < 750. I think something is wrong (the red line starts too low and you’re calculating/training something incorrectly), but I can’t know until you plot both the red and green for x < 750. 
3. I’m quite confused how you can possibly compute FTE for the Random Forest. It should be (single task N-XOR generalization error) /(multitask N-XOR generalization error). Where are you getting the single task N-XOR generalization error? It’s never computer on the fig plots.

**Review by levinwil — CHANGES_REQUESTED** [review]
Please see above comments

**Comment by jdey4** [comment]
I think, we agreed not to show <750 in the x axis for the top middle plot.

**Comment by jdey4** [comment]
I calculated the FTE for naive forest a long time ago according to jovo's definition. It was the ratio of (error from nxor forest)/(multitask error).

**Comment by levinwil** [comment]
“ It was the ratio of (error from nxor forest)/(multitask error).”

Are these generalization errors on NXOR?

**Comment by jdey4** [comment]
I am confused about your comment no 2. I obviously have xor transformer for the red line when I start for the nxor task. I think it is performing in the desired way.

**Comment by jdey4** [comment]
yes, generalization error.

**Comment by jdey4** [comment]
And we cannot show <750 for the x-axis. If we don't have any data nxor task, we cannot predict on nxor task. There will be no head for that task in the decider.

**Comment by levinwil** [comment]
1. Is the generalization error on NXOR? It should be for computing FTE. 
2. I see now that I was wrong in comment 2. My initial intuition was incorrect.

**Comment by jdey4** [comment]
Yes, it was the single task generalization error for nxor. I used this error to compute FTE for both L2F and RF.

**Comment by levinwil** [comment]
Okay. That sounds good. Please change Naive Forest to Random Forest and then everything should be all good.

**Comment by jdey4** [comment]
@levinwil I forgot to ask in the meeting what should naive BTE and naive FTE be named then?

**Comment by levinwil** [comment]
IMO “Random Forest {F, B}TE” would work

**Review by levinwil — APPROVED** [review]
This seems good - I'm not quite sure about the figure names, but we can change that later

**Pull request merged**
