### PR TITLE
XOR_RXOR Tutorial completed

### LINKED ISSUE #330: Create xor-rxor tutorial notebook using Jayanta's code
I plan to:

- [x] Create a notebook similar to [Emily's for xor-nxor](https://github.com/neurodata/ProgLearn/blob/main/docs/tutorials/xor_nxor_exp.ipynb)

- [x] Use code from [Jayanta's notebook](https://github.com/neurodata/ProgLearn/blob/staging/benchmarks/parity_experiment/experiment.ipynb)

### PR DESCRIPTION
**Pull request by bstraus1**
#### Reference issue

Closes #330 

#### Type of change

Documentation

#### What does this implement/fix?

Completed and added the xor_rxor tutorial and associated functions file.

### CODE REVIEW

**Comment by bstraus1** [comment]
@levinwil Will you please link this to issue #330.

**Comment by levinwil** [comment]
@bstraus1 Done.

**Comment by levinwil** [comment]
@bstraus1 Please add this tutorial to the netlify docs folder tutorials rst file. See #365 for instructions.

**Comment by bstraus1** [comment]
@levinwil Done

**Comment by levinwil** [comment]
1. Match the naming convention of the N-XOR tutorial in the docs and headers
2. Fix the latex equations to render correctly in netlify. 

You should just follow the N-XOR tutorial and make a slight modification in that of the rotation angle, the text description, and nothing else.

**Review by PSSF23 — COMMENTED** [review]
For #356, maybe make a shorter title (it will show up in Netlify menu) and remove the blank cell at the end?

**Comment by bstraus1** [comment]
@PSSF23 @levinwil How do I see the netlify view so I know what to change?

**Comment by levinwil** [comment]
@bstraus1 As mentioned, see #365 for instructions on how to view netlify. Go to the checks and go to the netlify checks then click on "details" on the right.

**Comment by bstraus1** [comment]
@levinwil Will do. Just note that #365 was not mentioned until you mentioned it. It is very helpful.

**Comment by bstraus1** [comment]
@levinwil Alright, I think it's better now.

**Comment by PSSF23** [comment]
@bstraus1 please fix x-axis for last graph & remove empty cell.

**Comment by bstraus1** [comment]
@PSSF23 Done 😃

**Review by PSSF23 — APPROVED** [review]
Fixed a small typo~ Will merge after tests.

**Pull request merged**
