### PR TITLE
Implement kappa and run figure 1

### PR DESCRIPTION
**Pull request by EYezerets**
#### Reference issue
Closes issue [321 ](https://github.com/neurodata/ProgLearn/issues/321)(again): Run UF figure 1 tutorial with real parameters 
Further addresses issue [62] (https://github.com/neurodata/ProgLearn/issues/62): re-write all the UF notebooks called ProgL repo functions

#### Type of change
Feature request, documentation

#### What does this implement/fix?
Implements kappa for finite sample correction in UncertaintyForest and voters.py.
Updates the tutorial and benchmarks notebooks for figure 1.
Starts a notebook for figure 2 (still in the works).

### CODE REVIEW

**Review by levinwil — APPROVED** [review]
1. Don’t save the pdf in fig1 tutorial 
2. The fig2 notebook is just fig1. Please remember that staging is supposed to be finished and polished work. Please do not commit anything that isn’t finished and polished. So please do not include your fig2 notebook in this PR.
3. Please make PR names more informative.

**Review by levinwil — CHANGES_REQUESTED** [review]
Please see above.

**Comment by EYezerets** [comment]
Got it, I'll delete those for this PR, sorry.

**Comment by EYezerets** [comment]
@levinwil Any further concerns I can address? :)

**Comment by levinwil** [comment]
Nope! You're all good. I'll approve and merge.

**Review by levinwil — APPROVED** [review]

**Review by levinwil — APPROVED** [review]

**Comment by levinwil** [comment]
@EYezerets Please update the tests to account for the fact that we've changed finite_sample_correction -> kappa

**Comment by EYezerets** [comment]
Hi @levinwil yes, happy to do that, I'm trying to change the file test_forest.py but I'm unfamiliar with this syntax. 
First, I am changing line 37 to say
`assert "kappa" in list(l2f.pl_.default_voter_kwargs.keys())`
Should I just remove line 38 since we don't want to require kappa to be any particular value? Or should I check that it's set to the default ("default", or np.inf?)
`assert l2f.pl_.default_voter_kwargs["kappa"] == False`

Also, I'm changing line 48 to say this:
`        l2f = LifelongClassificationForest(default_kappa=True)`

And line 49, do I want to check if kappa is on? I.e. that it is not np.inf? Or check if it is at the default value?
`        assert l2f.pl_.default_voter_kwargs == {"kappa": 'default'}` (previously it checked if finite_sample_correction was True

**Comment by levinwil** [comment]
1. If you're unfamiliar with the syntax, please look it up. 
2. Line 37 change is good. 
3. Check to make sure kappa is set to the default value
4. Line 48 change is good
5. Check to make sure it is the default value.

**Comment by levinwil** [comment]
@EYezerets The pytest failed on the following line:

l2f = LifelongClassificationForest(default_kappa=True)
assert l2f.pl_.default_voter_kwargs == {"kappa": np.inf}

Please make sure you change the kappa parameter to the instantiation of l2f from `True` to `np.inf`
Also, please make sure tests pass locally before committing/pushing

**Comment by EYezerets** [comment]
Thanks @levinwil, sorry I didn't get around to fixing that earlier this morning. I also apologize for the overabundance of commits - I'm having trouble running things on my machine without it changing the metadata to the wrong python version, so I have been committing it and testing on AWS (only briefly, then switching off the instance as soon as I'm done). I am still trying to fix the metadata problem, but this is my bandaid solution in the meantime

**Pull request merged**
