### PR TITLE
Scene Segmentation on ISIC using RF

### PR DESCRIPTION
**Pull request by amyvanee**
#### Reference issue
Continued progress on issue #39 on scene segmentation.

#### Type of change
Added
- tutorial notebook (scene_segmentation_rf_ISIC_tutorial.ipynb)
- tutorial functions (scene_segmentation_rf_ISIC_tutorial_functions.py)
- updated tutorial list (tutorials.rst)

Fixed black formatting of documents
- benchmarks/sims/spiral_sim.py 
- proglearn/tests/test_system.py
- proglearn/cifar_exp/experiment_varying_task_sample.py

#### What does this implement/fix?
Added another tutorial on scene segmentation using rf on ISIC dataset and fixed formatting of pre-existing files

#### Additional information
Neuro Data Design II, Spring 2022

### CODE REVIEW

**Review by PSSF23 — COMMENTED** [review]
@amyvanee you need to also comment what other files you corrected to pass the style checks.

**Comment by jdey4** [comment]
This file belongs to docs/tutorial, right?

**Comment by amyvanee** [comment]
> @amyvanee you need to also comment what other files you corrected to pass the style checks.

Updated my comment, thank you!

**Comment by jdey4** [comment]
I see 2 scene segmentation tutorials in docs/tutorial which should be in docs/experiment.

**Comment by amyvanee** [comment]
> This file belongs to docs/tutorial, right?

Yes! They were from benchmarks/cifar_exp, proglearn/tests and proglearn/sims

**Comment by amyvanee** [comment]
> I see 2 scene segmentation tutorials in docs/tutorial which should be in docs/experiment.

should these go under experiments instead? The notebooks we had previously were placed under tutorial?

**Comment by jdey4** [comment]
@amyvanee I would get rid of the "Dimensions of Images" blocks. The scatter plots are not informative. And why does the precision-recall curve show some dots instead of a continuous curve?

**Comment by jdey4** [comment]
> > I see 2 scene segmentation tutorials in docs/tutorial which should be in docs/experiment.
> 
> should these go under experiments instead? The notebooks we had previously were placed under tutorial?

@amyvanee they should be in the experiments folder. The location for the current PR is correct. But it was not correct for the PRs last semester.

**Comment by amyvanee** [comment]
> > > I see 2 scene segmentation tutorials in docs/tutorial which should be in docs/experiment.
> > 
> > 
> > should these go under experiments instead? The notebooks we had previously were placed under tutorial?
> 
> @amyvanee they should be in the experiments folder. The location for the current PR is correct. But it was not correct for the PRs last semester.

Sounds good, thank you! I also fixed the precision-recall curve and removed the unnecessary information about the dimensions of images.

**Review by PSSF23 — COMMENTED** [review]
Removed everything related to `tutorials` as the notebook is in `experiments`.

**Review by PSSF23 — CHANGES_REQUESTED** [review]
Never mind. It seems that Jayanta disagreed earlier. So you can revert my commits and fix two files' positions.

**Review by PSSF23 — CHANGES_REQUESTED** [review]
Function file is in the wrong folder.

**Comment by amyvanee** [comment]
> @amyvanee Check your website preview and fix the math equation. Other than that LGTM.

Fixed, thank you!!

**Review by PSSF23 — APPROVED** [review]
@jdey4 Your comments?

**Review by jdey4 — APPROVED** [review]

**Pull request merged**
