### PR TITLE
Optimize UncertaintyForest() notebooks and add Figure 2 tutorial 

### PR DESCRIPTION
**Pull request by EYezerets**
#### Reference issue
Contributes to addressing [Issue 37](https://github.com/neurodata/ProgLearn/issues/37): make 3 tutorials to run the experiments from uncertainty-forests

#### Type of change

Documentation and Bug Fix

#### What does this implement/fix?

This creates a new tutorial to run Figure 2 from [ this paper](https://arxiv.org/abs/1907.00325) with a small dataset (similar to the tutorial created by @bstraus1 for Figure 1). The functions called by the Figure 2 tutorial are located in unc_forest_tutorials_functions.py so as not to clutter the notebook. 
I also implemented a small bug fix to make sure `predict_proba()` in `UncertaintyForest()` can run by setting `self.lf_` in the `__init__()` function.

### CODE REVIEW

**Review by PSSF23 — COMMENTED** [review]
I don't think any output file should be uploaded? @EYezerets

**Comment by EYezerets** [comment]
@PSSF23 Oh good point, yes I can remove the pkl files, but I will leave an empty output folder if that's all right

**Comment by PSSF23** [comment]
@EYezerets I believe the best thing, if feasible, would be having everything contained in the notebook and leaving no output file at all. So instead of saving the outputs as pickle files and loading again, the program uses them directly to generate the figures.

That was a [suggestion](https://github.com/neurodata/ProgLearn/pull/149#issuecomment-700886225) Will gave to me and Yuta when we simplified the benchmark tutorials (`random_class_exp` & `label_shuffle_exp`). @levinwil do you think the rule apply here as well?

**Comment by levinwil** [comment]
@EYezerets @PSSF23 Yes I agree with that suggestion!

**Comment by levinwil** [comment]
@EYezerets Any updates?

**Comment by EYezerets** [comment]
Hi @levinwil , just made a few edits today so it no longer outputs pkl files and still plots Figure 2 with the test parameters. Please kindly let me know if there's anything else needed before merging!

**Comment by PSSF23** [comment]
@EYezerets Please add your tutorial name to `docs/tutorials.rst` and remove the last blank cell in the notebook, thanks.

**Comment by PSSF23** [comment]
Actually, could you rewrite all the `uncertaintyforest` tutorials' introduction to have a consistent style? These three should be a set I believe?

**Comment by EYezerets** [comment]
@PSSF23 Yes I can do that! (Just to clarify, the first two tutorials were created by Ben, and once I make the one for Figure 3, there will be 4 uncertainty forest tutorials total. I will update the existing 3 tutorials to be as consistent as possible, and please let me know if you have additional feedback.)

**Comment by EYezerets** [comment]
@PSSF23 Could I please verify with you whether the way I wrote the figure 2 tutorial matches up better with the Netlify site requirements? That was my goal, and I was planning to modify the other two notebooks to be consistent with that.

**Comment by levinwil** [comment]
@EYezerets On the checks, go to any of the Netlify checks. Click on "details" on the right. Then navigate to your tutorial. You'll see how it renders.

**Comment by PSSF23** [comment]
@EYezerets Basically, what is going to show up on the Netlify website would be "#" formatted title and "##" formatted subtitles. I think what you have on fig2 tutorial should be mostly good. And you must add your tutorial name to `docs/tutorials.rst` for it to show up at all. Check out more at #356

**Comment by PSSF23** [comment]
I resolved the `rst` conflicts. Feel free to add more changes and let us know when you are done @EYezerets

**Comment by EYezerets** [comment]
Wait just a moment! I just ran the notebook so I have output for it again!

**Comment by EYezerets** [comment]
Thank you @PSSF23

**Comment by PSSF23** [comment]
@EYezerets I would prefer a version without the warnings but the website is looking good! And there is still a blank cell at the end of `uncertaintyforest_running_example`~

**Comment by EYezerets** [comment]
Ah hmm sorry about the warnings - it may be a side effect of running on AWS, but my computer is not unserializing parallel tasks if I run the tutorial locally.
I can take out the extra cell in that notebook right away - thanks for catching that!

**Comment by levinwil** [comment]
@PSSF23 This looks good to me. What do you think?

**Review by PSSF23 — APPROVED** [review]
@levinwil I think it's good, too! Everything I know is addressed.

**Comment by EYezerets** [comment]
That's awesome! Thank you both! @PSSF23 @levinwil

**Pull request merged**
