### PR TITLE
Removed an extra link to the installation guide in docs

### PR DESCRIPTION
**Pull request by levinwil**

### CODE REVIEW

**Review by PSSF23 — COMMENTED** [review]
@levinwil Sorry for the little-late notice, but `sample_size_experiment` should be included as well?

**Comment by levinwil** [comment]
@PSSF23 I don't understand what you are asking.

**Comment by PSSF23** [comment]
@levinwil I mean this new tutorial: https://github.com/neurodata/ProgLearn/blob/staging/docs/tutorials/sample_size_experiment.ipynb

Should it be included in the `rst` list as well?

**Comment by levinwil** [comment]
@PSSF23 No I don't think so. It's not a tutorial for ProgLearn, so I don't think we should display it in the docs. But it still needs to live here, because jovo wants it to.

**Review by PSSF23 — APPROVED** [review]

**Pull request merged**
