### PR TITLE
Added bte_with_cpd experiment tutorial notebook

### PR DESCRIPTION
**Pull request by williamrxu**
#### Reference issue
Closes Domain Adaptation with CPD Algorithm #379 

#### Type of change
Documentation

#### What does this implement/fix?
Added tutorial notebook demonstrating the application of the CPD algorithm (https://arxiv.org/pdf/0905.2635.pdf) to improving backward transfer efficiency when given XOR and R-XOR tasks. Notebook: https://nbviewer.jupyter.org/github/williamrxu/ProgLearn/blob/staging/docs/tutorials/bte_with_cpd_exp.ipynb

#### Additional information
This is my Sprint 1 PR completing issue Domain Adaptation with CPD Algorithm #379.

### CODE REVIEW

**Comment by levinwil** [comment]
This looks great to me! @PSSF23 Do you have any comments?

**Review by PSSF23 — COMMENTED** [review]
@levinwil I was going to mention the `tutorial.rst` but nothing more!

**Comment by williamrxu** [comment]
@levinwil Added! I inserted it alphabetically. Please let me know if you want it to be last on the list or if I did not add it correctly.

**Comment by PSSF23** [comment]
@williamrxu the order doesn't have to be very strict, but I believe everything must be after the installation guide.

So just move it one step below and everything good.

**Comment by PSSF23** [comment]
@levinwil do you think the tutorial name is accurate? I think something lie `xor_rxor_cpd` might be more relevant?

**Comment by levinwil** [comment]
@williamrxu I agree with @PSSF23. I think you should mentioned that it's on XOR/RXOR in the notebook filename. I also agree with @PSSF23 on the order of the notebooks: everything should be after the installation guide.

**Comment by williamrxu** [comment]
@levinwil @PSSF23 updated as requested.

- Update experiment name to xor_rxor_with_cpd
- Moved experiment to last on the list on tutorials.rst

**Review by PSSF23 — APPROVED** [review]
@williamrxu I corrected your tutorial name in the `rst` file, and everything should be good now.

**Comment by levinwil** [comment]
@PSSF23 i think this is ready to be merged into staging once it passes the tests. Do you agree?

**Comment by PSSF23** [comment]
@levinwil yes.

**Pull request merged**
