### PR TITLE
Updated and refined xor_xnor experiment notebook

### LINKED ISSUE #301: Refine the xor_xnor experiment tutorial
Specifically, I will:

- [x] Update the notebook using [Jayanta's notebook](https://github.com/neurodata/ProgLearn/blob/staging/benchmarks/parity_experiment/experiment.ipynb)
- [x] Ensure that there are no warnings/unwanted outputs in the notebook (currently there are some)
- [x] Go line by line with the code, explaining each step
- [x] Move long functions to a separate .py file to improve readability
- [x] Restrict sample sizes in the final figure to X>750
- [x] Remove progress print statements throughout the code
- [x] Find and replace all "FTE" with "BTE", and vice versa in the last figure

### PR DESCRIPTION
**Pull request by bstraus1**
Resolves #301 

-Updated the notebook using Jayanta's notebook
-Ensured that there are no warnings/unwanted outputs in the notebook (currently there are some)
-Went line by line with the code, explaining each step
-Moved long functions to a separate .py file to improve readability
-Restricted sample sizes in the final figure to X>750
-Removed progress print statements throughout the code

### CODE REVIEW

**Comment by bstraus1** [comment]
@levinwil Will you link this PR to Issue #301?

**Review by levinwil — CHANGES_REQUESTED** [review]
Could you please fix the legend? Maybe reduce the fantasize in the legend?

**Comment by bstraus1** [comment]
@levinwil Do you mean font size?

**Comment by levinwil** [comment]
@bstraus1 Yes haha. Strange autocorrect.

**Comment by bstraus1** [comment]
@levinwil Done

**Review by levinwil — APPROVED** [review]

**Pull request merged**
